version: '3'
services:
  db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - auth_pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - "5432"
  redis:
    image: redis:7.0-alpine
    volumes:
      - redis_data:/data
    expose:
      - "6379"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger


  auth_service:
    build: ../flask-solution/
    expose:
      - "5500"
    depends_on:
     - db
     - redis
    env_file:
      - ./.env
  nginx:
    image: nginx:1.23.1-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - auth_service
    ports:
      - "80:80"


volumes:
  auth_pgdata:
  redis_data:
